[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ascents"
version = "1.2.0"
requires-python = ">=3.12.6"

[project.scripts]
ascents = "ascents.__main__:main"
