[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ascents"
version = "0.1.0"
requires-python = ">=3.11.9"

[project.scripts]
ascents = "ascents.__main__:main"
